name: CI
on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: echo ${{ env.environment }}
      
      - name: Checkout Repositorio
      - uses: actions/checkout@v3

      - name: Executar Build do projeto
        run: Inicando Execução Build !

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven Clean
        run: mvn clean
      
      - name: Maven Compile
        run: mvn compile
      
      - name: Maven Compile
        run: mvn compile


