name: CI
on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: | 
          echo Iniciando Build
          echo Branch ${{ branch github.ref_name }}
          echo Gatilho ${{ github.ref_name }}

