name: CI
on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: | 
          echo Iniciando Build
          echo Branch ${{ github.ref_name }}
          echo Evento ${{ github.event_name }}
          echo Ambiente ${{ env.environment }}
      
      - name: Checkout Repositorio
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: mvn -B clean install

